name: pipeline
on: 
  push:
    branches:
      - node 
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: hello word
        run: node index.jv
  
